<#
.SYNOPSIS
    Installs the DevLens Android APK directly to a connected Android phone over USB.
.DESCRIPTION
    Auto-detects adb, verifies device authorization, finds or accepts an APK file,
    and installs/launches DevLens on the target phone.
.PARAMETER ApkPath
    Optional explicit path to the .apk file.
#>
param (
    [string]$ApkPath = ""
)

Write-Host "=========================================" -ForegroundColor Cyan
Write-Host "  DevLens Android Phone Installer (ADB)  " -ForegroundColor Cyan
Write-Host "=========================================" -ForegroundColor Cyan

# 1. Locate adb.exe
$adb = "adb"
$adbFound = $false

if (Get-Command "adb" -ErrorAction SilentlyContinue) {
    $adbFound = $true
} else {
    $candidates = @(
        "$env:LOCALAPPDATA\Android\Sdk\platform-tools\adb.exe",
        "$env:ANDROID_HOME\platform-tools\adb.exe",
        "$env:ANDROID_SDK_ROOT\platform-tools\adb.exe",
        "C:\Android\Sdk\platform-tools\adb.exe"
    )
    foreach ($cand in $candidates) {
        if (Test-Path $cand) {
            $adb = $cand
            $adbFound = $true
            break
        }
    }
}

if (-not $adbFound) {
    Write-Host "[ERROR] adb.exe could not be found." -ForegroundColor Red
    Write-Host "Please ensure Android SDK Platform Tools is installed or add adb to your PATH." -ForegroundColor Yellow
    exit 1
}

Write-Host "[+] Using ADB: $adb" -ForegroundColor Green

# 2. Check connected devices
Write-Host "[*] Checking for connected Android devices..." -ForegroundColor Gray
$devicesOutput = & $adb devices
$lines = $devicesOutput -split "`r?`n" | Where-Object { $_ -match "\bdevice\b" -and $_ -notmatch "List of devices" }

if (-not $lines -or $lines.Count -eq 0) {
    Write-Host "[!] No authorized Android device detected over USB." -ForegroundColor Yellow
    Write-Host ""
    Write-Host "Please follow these steps on your phone:" -ForegroundColor White
    Write-Host "  1. Connect your phone to your PC via USB cable." -ForegroundColor Gray
    Write-Host "  2. On your phone, go to Settings -> About Phone -> Tap 'Build Number' 7 times to enable Developer Options." -ForegroundColor Gray
    Write-Host "  3. Go to Settings -> System / Developer Options -> Enable 'USB Debugging'." -ForegroundColor Gray
    Write-Host "  4. Unlock your phone screen and tap 'Always allow from this computer' if prompted." -ForegroundColor Gray
    Write-Host "  5. Re-run this script." -ForegroundColor Gray
    Write-Host ""
    exit 1
}

Write-Host "[+] Connected device(s) found:" -ForegroundColor Green
foreach ($line in $lines) {
    Write-Host "    - $line" -ForegroundColor Cyan
}

# 3. Locate target APK
if (-not $ApkPath) {
    $candidates = @(
        "$PSScriptRoot\..\mobile\android\app\build\outputs\apk\debug\app-debug.apk",
        "$PSScriptRoot\..\mobile\android\app\build\outputs\apk\release\app-release.apk",
        "$PSScriptRoot\..\devlens-v0.1.0-debug.apk",
        "$PSScriptRoot\..\devlens.apk",
        "$HOME\Downloads\devlens*.apk",
        "$HOME\Downloads\app-debug*.apk"
    )

    foreach ($pattern in $candidates) {
        $resolved = Get-ChildItem -Path $pattern -ErrorAction SilentlyContinue | Select-Object -First 1
        if ($resolved) {
            $ApkPath = $resolved.FullName
            break
        }
    }
}

if (-not $ApkPath -or -not (Test-Path $ApkPath)) {
    Write-Host "[!] No APK file found automatically." -ForegroundColor Yellow
    Write-Host "You can pass the APK path explicitly:" -ForegroundColor White
    Write-Host "  .\scripts\install-to-phone.ps1 -ApkPath path\to\your-app.apk" -ForegroundColor Gray
    Write-Host ""
    Write-Host "Or download the APK generated by the GitHub Actions CI pipeline from your repository's Releases or Actions tab." -ForegroundColor White
    exit 1
}

Write-Host "[+] Installing APK: $ApkPath" -ForegroundColor Green
& $adb install -r "$ApkPath"

if ($LASTEXITCODE -eq 0) {
    Write-Host "[SUCCESS] DevLens successfully installed on your phone!" -ForegroundColor Green
    Write-Host "[*] Launching DevLens on your phone..." -ForegroundColor Gray
    & $adb shell monkey -p com.devlens.mobile -c android.intent.category.LAUNCHER 1 | Out-Null
    Write-Host "[✓] App launched successfully!" -ForegroundColor Green
} else {
    Write-Host "[ERROR] Installation failed. Check phone permissions or disable Play Protect prompt if blocked." -ForegroundColor Red
}
